version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_sales
        description: sales of Greenweez / we have one row per 'products_id' found in each 'orders_id'

        # Freshness testing - make sure to fill in the ...
        freshness:
          warn_after: 
            count: 90
            period: day
        loaded_at_field: CAST(date_date AS TIMESTAMP)

        tests:
          - unique:
              column_name: "orders_id || '-' || pdt_id"
          - not_null:
              column_name: "orders_id || '-' || pdt_id"

      - name: ship
        identifier: raw_ship
        description: ship of Greenweez / we have on row per 'orders_id' - 'product_id' with revenue and quantity
        columns:
        - name: orders_id
          description: primary key for this table (Integer ID of order)
          tests:
            - unique
            - not_null

      - name: product
        identifier: raw_product
        description: product of Greenweez / we have one row per 'product_id' with 'purchase_price'
        columns:
        - name: products_id
          description: primary key for this table (Integer ID of product)
          tests:
            - unique
            - not_null
